spring:
  application:
    name: CRM
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariPool-1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8090
#  liquibase:
#    change-log: db/changelog/db.changelog-master.xml